# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
