# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrank',
            name='picture_fk',
        ),
        migrations.AddField(
            model_name='userrank',
            name='picture_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
