# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userrank_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='title',
            field=models.CharField(default='Anfänger', max_length=200),
        ),
    ]
