# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userrank_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='title',
            field=models.CharField(default=b'Beginner', max_length=200),
        ),
    ]
