# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.IntegerField(default=b'1'),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='title',
            field=models.CharField(default=b'Neuling', max_length=200),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
