# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
