# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170117_1835'),
        ('account', '0008_auto_20170115_2226'),
    ]

    operations = [
    ]
