# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20170117_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='title',
            field=models.CharField(default='Neuling', max_length=200),
        ),
    ]
