# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20161214_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=b'', max_length=200)),
                ('label', models.SlugField(unique=True)),
                ('quiz_id', models.IntegerField(default=1)),
                ('lobby_password', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInLobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('lobby_id', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
