# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20161214_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergebnis',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
