# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_lobby_userinlobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
