# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_lobby_userinlobby'),
        ('quiz', '0022_ergebnis_user_id'),
    ]

    operations = [
    ]
