# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_merge_20170102_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
