# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20170102_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestionPropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(default=b'essay', max_length=200)),
                ('quizfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestionPropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_question_text', models.CharField(max_length=200)),
                ('answer_text1', models.CharField(default=b'', max_length=200)),
                ('answer_text2', models.CharField(default=b'', max_length=200)),
                ('answer_text3', models.CharField(default=b'', max_length=200)),
                ('answer_text4', models.CharField(default=b'', max_length=200)),
                ('correct_answer_1', models.BooleanField(help_text=b'*       clear = False | Checked = True')),
                ('correct_answer_2', models.BooleanField(help_text=b'*       clear = False | Checked = True')),
                ('correct_answer_3', models.BooleanField(help_text=b'*       clear = False | Checked = True')),
                ('correct_answer_4', models.BooleanField(help_text=b'*       clear = False | Checked = True')),
                ('question_type', models.CharField(default=b'multiplechoice', max_length=200)),
                ('quizfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestionPropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_question_text', models.CharField(max_length=200)),
                ('answer_text1', models.CharField(default=b'', max_length=200)),
                ('answer_text2', models.CharField(default=b'', max_length=200)),
                ('answer_text3', models.CharField(default=b'', max_length=200)),
                ('answer_text4', models.CharField(default=b'', max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('question_type', models.CharField(default=b'singlechoice', max_length=200)),
                ('quizfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TFQuestionPropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_question_text', models.CharField(max_length=200)),
                ('true_or_false', models.BooleanField(default=False, help_text=b'*clear = False | Checked = True')),
                ('question_type', models.CharField(default=b'truefalse', max_length=200)),
                ('quizfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
