# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_essayquestionpropose_multiplechoicequestionpropose_singlechoicequestionpropose_tfquestionpropose'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestionpropose',
            name='user',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestionpropose',
            name='user',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestionpropose',
            name='user',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='tfquestionpropose',
            name='user',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
