# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20170109_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposeessayquestion',
            name='user',
            field=models.IntegerField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='user',
            field=models.IntegerField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='user',
            field=models.IntegerField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='user',
            field=models.IntegerField(default=b'', max_length=200),
        ),
    ]
