# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20170111_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dozent',
            field=models.IntegerField(max_length=50),
        ),
    ]
