# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20170112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dozent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ergebnis',
            name='quiz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proposeessayquestion',
            name='user',
            field=models.IntegerField(default=b''),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='user',
            field=models.IntegerField(default=b''),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='user',
            field=models.IntegerField(default=b''),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='user',
            field=models.IntegerField(default=b''),
        ),
    ]
