# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_lobby_current_question'),
        ('quiz', '0032_auto_20170112_1436'),
    ]

    operations = [
    ]
