# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20170115_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinlobby',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
