# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_merge_20170117_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposeessayquestion',
            name='dozent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposeessayquestion',
            name='question_type',
            field=models.CharField(default='essay', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposeessayquestion',
            name='user',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='answer_text1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='answer_text2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='answer_text3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='answer_text4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='correct_answer_1',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='correct_answer_2',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='correct_answer_3',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='correct_answer_4',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='dozent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='question_type',
            field=models.CharField(default='multiplechoice', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposemultiplechoicequestion',
            name='user',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='answer_text1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='answer_text2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='answer_text3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='answer_text4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='dozent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='question_type',
            field=models.CharField(default='singlechoice', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposesinglechoicequestion',
            name='user',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='dozent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='question_type',
            field=models.CharField(default='truefalse', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='true_or_false',
            field=models.BooleanField(default=False, help_text='*clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='proposetfquestion',
            name='user',
            field=models.IntegerField(default=''),
        ),
    ]
