# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_userinlobby_current_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='current_question',
        ),
    ]
